# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:15.8.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/anvil-deploy
    steps:

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-
      - run:
          name: Checkout Client-APIs Repo
          command: cd .. && git clone git@github.com:anvilproject/client-apis.git --branch pyAnVIL --single-branch && cd client-apis

      - run:
          name: Install npm
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Setup Environment Variables
          command: echo "export GATSBY_ENV=$CIRCLE_BRANCH" >> $BASH_ENV

      - run:
          name: Gatsby Build
          command: npm run build-ci

      - persist_to_workspace:
                    # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
                    # taken to be the root directory of the workspace.
                    root: ~/anvil-deploy
                    # Must be relative path from root
                    paths:
                      - public

  deploy:
    docker:
          # specify the version you desire here
          - image: circleci/node:10.16

    working_directory: ~/anvil-deploy
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/anvil-deploy
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install

      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase  deploy -P "$BRANCH" --token "$FIREBASE_TOKEN"

workflows:
    version: 2
    build-n-deploy-staging:
      jobs:
        - build:
            filters:
              branches:
                only:
                  - staging
                  - ux-dev
            context: anvil-portal-staging
        - deploy:
            requires:
              - build
            filters:
              branches:
                only:
                  - staging
                  - ux-dev
            context: anvil-portal-staging
    build-n-deploy-prod:
      jobs:
        - build:
            filters:
              branches:
                only: master
            context: anvil-portal-prod
        - deploy:
            requires:
              - build
            filters:
              branches:
                only: master
            context: anvil-portal-prod